/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2020-09-09 11:41:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.customer;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class adminmain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/p01/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1598681847341L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("#cart {\r\n");
      out.write("\twidth: 800px;\r\n");
      out.write("\theight: 500px;\r\n");
      out.write("\tborder: 2px solid red;\r\n");
      out.write("\toverflow: auto;\r\n");
      out.write("\tbackground: white;\r\n");
      out.write("\tjustify-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#map {\t\r\n");
      out.write("\twidth: 800px;\r\n");
      out.write("\theight: 300px;\r\n");
      out.write("\tborder: 2px solid red;\r\n");
      out.write("\toverflow: auto;\r\n");
      out.write("\tbackground: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#cart >div> img {\r\n");
      out.write("\twidth:90px;\r\n");
      out.write("\theight:60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#cart > div {\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#but {\r\n");
      out.write("\tposition:relative;\r\n");
      out.write("\tleft:500px;\r\n");
      out.write("\tbored-radius:50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("\r\n");
      out.write("<title>어서오세요. M마트입니다.</title>\r\n");
      out.write("<meta content=\"\" name=\"descriptison\">\r\n");
      out.write("<meta content=\"\" name=\"keywords\">\r\n");
      out.write("\r\n");
      out.write("<!-- Favicons -->\r\n");
      out.write("<link href=\"customer/assets/img/favicon.png\" rel=\"icon\">\r\n");
      out.write("<link href=\"customer/assets/img/apple-touch-icon.png\"\r\n");
      out.write("\trel=\"apple-touch-icon\">\r\n");
      out.write("\r\n");
      out.write("<!-- Google Fonts -->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=https://fonts.googleapis.com/css?family=Inconsolata:400,500,600,700|Raleway:400,400i,500,500i,600,600i,700,700i\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Vendor CSS Files -->\r\n");
      out.write("<link href=\"customer/assets/vendor/bootstrap/css/bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link href=\"customer/assets/vendor/icofont/icofont.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link href=\"customer/assets/vendor/aos/aos.css\" rel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"customer/assets/vendor/line-awesome/css/line-awesome.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"customer/assets/vendor/owl.carousel/assets/owl.carousel.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Template Main CSS File -->\r\n");
      out.write("<link href=\"customer/assets/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- =======================================================\r\n");
      out.write("  * Template Name: MyPortfolio - v2.1.0\r\n");
      out.write("  * Template URL: https://bootstrapmade.com/myportfolio-bootstrap-portfolio-website-template/\r\n");
      out.write("  * Author: BootstrapMade.com\r\n");
      out.write("  * License: https://bootstrapmade.com/license/\r\n");
      out.write("  ======================================================== -->\r\n");
      out.write("</head>\r\n");
      out.write("<script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var products = null;\r\n");
      out.write("\r\n");
      out.write("function display(data){\r\n");
      out.write("\t$(data).each(function(index,data){\r\n");
      out.write("\tvar result = '';\r\n");
      out.write("\tresult += '<div class=\"item ' +data.category+ ' col-sm-3 col-md-2 col-lg-3 mb-3\">';\r\n");
      out.write("\tresult += '<div class=\"item-wrap fancybox\">';\r\n");
      out.write("\tresult += '<div class=\"work-info\" id=\"menu\">';\r\n");
      out.write("\tresult += '<div num=\"'+index+'\">';\r\n");
      out.write("\tresult += '<p>'+data.name+'</p>';\r\n");
      out.write("\tresult += '<p>'+data.stock+'</p>';\r\n");
      out.write("\tresult += '<p>'+data.price+'</p>';\r\n");
      out.write("\tresult += '</div>';\r\n");
      out.write("\tresult += '</div>';\r\n");
      out.write("\tresult += '<img class=\"img-fluid\" src=\"customer/img/'+data.img+'\">'\r\n");
      out.write("\tresult += '</div>';\r\n");
      out.write("\tresult += '</div>';\r\n");
      out.write("\t$('#portfolio-grid').append(result);\r\n");
      out.write("\t});\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function getMain(){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("/* \t\ttype:'get', */\r\n");
      out.write("\t\t  url: 'menuselect.mc',\r\n");
      out.write("\t\t  dataType: 'json',\r\n");
      out.write("\t\tasync:false,\r\n");
      out.write("\t\tsuccess: function(ja){\r\n");
      out.write("\t\t\tproducts = ja;\r\n");
      out.write("\t\t\tdisplay(ja);\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror: function(){\r\n");
      out.write("\t\t\talert('get Error.........');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("function cart(n){\r\n");
      out.write("\tvar name = products[n].name;\r\n");
      out.write("\tvar price = products[n].price;\r\n");
      out.write("\tvar img = products[n].img;\r\n");
      out.write("\tvar count = products[n].count;\r\n");
      out.write("\tvar result = '';\r\n");
      out.write("\t\tresult += '<div num=\"'+n+'\" id=\"choose'+n+'\">';\r\n");
      out.write("\t\tresult += '<img src = \"customer/img/'+img+'\">';\r\n");
      out.write("\t\tresult += name+' '+price+' 개수 : '+count;\r\n");
      out.write("\t\tresult += '<button id=\"but\">X</button></div>';\r\n");
      out.write("\t$('#cart').append(result);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\tgetMain();\r\n");
      out.write("\t$('#menu > div').mouseover(function(){\r\n");
      out.write("\t\t$(this).css(\"cursor\", \"pointer\");\r\n");
      out.write("\t});\r\n");
      out.write("\t$('#menu > div').click(function(){\r\n");
      out.write("\t\tvar num = $(this).attr('num');\r\n");
      out.write("\t\tproducts[num].count += 1;\r\n");
      out.write("\t\tif(products[num].count == 1){\r\n");
      out.write("\t\tcart(num);\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t$('#choose'+num).remove();\r\n");
      out.write("\t\t\tcart(num);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t$('#cart').on('click', '#but', function(){\r\n");
      out.write("\t\tvar num = $(this).parent().attr('num');\r\n");
      out.write("\t\tif(products[num].count == 1) {\r\n");
      out.write("\t\t\t$(this).parent().remove();\r\n");
      out.write("\t\t\tproducts[num].count = 0;\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tproducts[num].count = products[num].count - 1;\r\n");
      out.write("\t\t\t$('#choose'+num).remove();\r\n");
      out.write("\t\t\tcart(num);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!-- ======= Navbar ======= -->\r\n");
      out.write("\t<div class=\"collapse navbar-collapse custom-navmenu\" id=\"main-navbar\">\r\n");
      out.write("\t\t<div class=\"container py-2 py-md-5\">\r\n");
      out.write("\t\t\t<div class=\"row align-items-start\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-2\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"custom-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"active\"><a href=\"main.mc\">홈</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"mypage.mc\">마이 페이지</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"contact.mc\">건의사항</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"logout.mc\">로그아웃</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"admin.mc\">관리자</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 d-none d-md-block  mr-auto\">\r\n");
      out.write("\t\t\t\t\t<div class=\"tweet d-flex\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"icofont-twitter text-white mt-2 mr-3\"></span>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<em>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginuser.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("님 안녕하세요 <br>\r\n");
      out.write("\t\t\t\t\t\t\t\t</em>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 d-none d-md-block\">\r\n");
      out.write("\t\t\t\t\t<h3>Hire Me</h3>\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\tLorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam\r\n");
      out.write("\t\t\t\t\t\tnecessitatibus incidunt ut officiisexplicabo inventore. <br>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">myemail@gmail.com</a>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<nav class=\"navbar navbar-light custom-navbar\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"main.mc\">M Mart</a> <a href=\"#\"\r\n");
      out.write("\t\t\t\tclass=\"burger\" data-toggle=\"collapse\" data-target=\"#main-navbar\">\r\n");
      out.write("\t\t\t\t<span></span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t<main id=\"main\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- ======= Works Section ======= -->\r\n");
      out.write("\t\t<section class=\"section site-portfolio\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row mb-5 align-items-center\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12 col-lg-6 mb-4 mb-lg-0\" data-aos=\"fade-up\">\r\n");
      out.write("\t\t\t\t\t\t<h2>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginuser.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("님 M 마트에 오신걸 환영합니다</h2>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"mb-0\">즐거운 쇼핑 되세요</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12 col-lg-6 text-left text-lg-right\"\r\n");
      out.write("\t\t\t\t\t\tdata-aos=\"fade-up\" data-aos-delay=\"100\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"filters\" class=\"filters\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" data-filter=\"*\" class=\"active\">All</a> <a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-filter=\".1\">Burger</a> <a href=\"#\" data-filter=\".2\">Side</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" data-filter=\".3\">Beverage</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"portfolio-grid\" class=\"row no-gutter\" data-aos=\"fade-up\"\r\n");
      out.write("\t\t\t\t\tdata-aos-delay=\"200\">\r\n");
      out.write("\t\t\t\t\t<!-- append -->\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t<div id=\"cart\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<!-- End  Works Section -->\r\n");
      out.write("\r\n");
      out.write("\t</main>\r\n");
      out.write("\t<!-- End #main -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<a href=\"#\" class=\"back-to-top\"><i class=\"icofont-simple-up\"></i></a>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Vendor JS Files -->\r\n");
      out.write("\t<script src=\"customer/assets/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"customer/assets/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\t<script src=\"customer/assets/vendor/jquery.easing/jquery.easing.min.js\"></script>\r\n");
      out.write("\t<script src=\"customer/assets/vendor/php-email-form/validate.js\"></script>\r\n");
      out.write("\t<script src=\"customer/assets/vendor/aos/aos.js\"></script>\r\n");
      out.write("\t<script src=\"customer/assets/vendor/isotope-layout/isotope.pkgd.min.js\"></script>\r\n");
      out.write("\t<script src=\"customer/assets/vendor/owl.carousel/owl.carousel.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Template Main JS File -->\r\n");
      out.write("\t<script src=\"customer/assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
