/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2020-09-10 01:01:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.customer;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class contactdetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("  <main id=\"main\">\r\n");
      out.write("\r\n");
      out.write("    <section class=\"section pb-5\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row mb-5 align-items-end\">\r\n");
      out.write("          <div class=\"col-md-6\" data-aos=\"fade-up\">\r\n");
      out.write("            <h2>Contact</h2>\r\n");
      out.write("            <p class=\"mb-0\">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam necessitatibus incidunt ut\r\n");
      out.write("              officiis explicabo inventore.\r\n");
      out.write("            </p>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-12 mb-5 mb-md-0\" data-aos=\"fade-up\">\r\n");
      out.write("\r\n");
      out.write("            <form action=\"admincontactupdate.mc\" method=\"post\" role=\"form\" class=\"php-email-form\">\r\n");
      out.write("\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <input type=\"hidden\" name=id value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${admincontactdetail.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly/>\r\n");
      out.write("                <div class=\"col-md-6 form-group\">\r\n");
      out.write("                  <label for=\"name\">이름</label>\r\n");
      out.write("                  <input type=\"text\" name=\"name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${admincontactdetail.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"form-control\" id=\"name\" data-rule=\"minlen:2\" data-msg=\"이름을 입력해주세요.\" readonly />\r\n");
      out.write("                  <div class=\"validate\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 form-group\">\r\n");
      out.write("                  <label for=\"name\">이메일</label>\r\n");
      out.write("                  <input type=\"email\" class=\"form-control\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${admincontactdetail.email }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"email\" id=\"email\" data-rule=\"email\" data-msg=\"Please enter a valid email\" readonly />\r\n");
      out.write("                  <div class=\"validate\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-12 form-group\">\r\n");
      out.write("                  <label for=\"name\">제목</label>\r\n");
      out.write("                  <input type=\"text\" class=\"form-control\" name=\"subject\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${admincontactdetail.subject }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"subject\" data-rule=\"required\" data-msg=\"제목을 입력해주세요.\" readonly />\r\n");
      out.write("                  <div class=\"validate\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-12 form-group\">\r\n");
      out.write("                  <label for=\"name\">내용</label>\r\n");
      out.write("                  <textarea class=\"form-control\" name=\"message\" cols=\"30\" rows=\"10\" data-rule=\"required\" data-msg=\"Please write something for us\" readonly>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${admincontactdetail.message }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("                  <div class=\"validate\"></div>\r\n");
      out.write("                  <input type=\"hidden\" name=regdate value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${admincontactdetail.regdate }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly/>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-md-6 form-group\">\r\n");
      out.write("                  <input type=\"button\" class=\"readmore d-block w-100\" value=\"글 목록\" onclick=\"location.href='contactselect.mc'\">\r\n");
      out.write("                </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-md-4 ml-auto order-2\" data-aos=\"fade-up\">\r\n");
      out.write("            <ul class=\"list-unstyled\">\r\n");
      out.write("              <li class=\"mb-3\">\r\n");
      out.write("                <strong class=\"d-block mb-1\">Address</strong>\r\n");
      out.write("                <span>203 Fake St. Mountain View, San Francisco, California, USA</span>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"mb-3\">\r\n");
      out.write("                <strong class=\"d-block mb-1\">Phone</strong>\r\n");
      out.write("                <span>+1 232 3235 324</span>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"mb-3\">\r\n");
      out.write("                <strong class=\"d-block mb-1\">Email</strong>\r\n");
      out.write("                <span>youremail@domain.com</span>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("  </main><!-- End #main -->\r\n");
      out.write("\r\n");
      out.write("  <!-- ======= Footer ======= -->\r\n");
      out.write("  <footer class=\"footer\" role=\"contentinfo\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-sm-6\">\r\n");
      out.write("          <p class=\"mb-1\">&copy; Copyright MyPortfolio. All Rights Reserved</p>\r\n");
      out.write("          <div class=\"credits\">\r\n");
      out.write("            <!--\r\n");
      out.write("            All the links in the footer should remain intact.\r\n");
      out.write("            You can delete the links only if you purchased the pro version.\r\n");
      out.write("            Licensing information: https://bootstrapmade.com/license/\r\n");
      out.write("            Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=MyPortfolio\r\n");
      out.write("          -->\r\n");
      out.write("            Designed by <a href=\"https://bootstrapmade.com/\">BootstrapMade</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-sm-6 social text-md-right\">\r\n");
      out.write("          <a href=\"#\"><span class=\"icofont-twitter\"></span></a>\r\n");
      out.write("          <a href=\"#\"><span class=\"icofont-facebook\"></span></a>\r\n");
      out.write("          <a href=\"#\"><span class=\"icofont-dribbble\"></span></a>\r\n");
      out.write("          <a href=\"#\"><span class=\"icofont-behance\"></span></a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer>\r\n");
      out.write("\r\n");
      out.write("  <a href=\"#\" class=\"back-to-top\"><i class=\"icofont-simple-up\"></i></a>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
