/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2020-09-11 14:55:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.customer;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/p01/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1598681847341L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("#cart {\r\n");
      out.write("   width: 650px;\r\n");
      out.write("   height: 400px;\r\n");
      out.write("   border-style: solid;\r\n");
      out.write("   border-color: #e9eaf1;\r\n");
      out.write("   border-width: 2px;\r\n");
      out.write("   overflow: auto;\r\n");
      out.write("   background: white;\r\n");
      out.write("   display: block;\r\n");
      out.write("   margin-top: 0px;\r\n");
      out.write("   margin-bottom: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#portfolio-grid > div > div > div > img {\r\n");
      out.write("\twidth : 100px;\r\n");
      out.write("\theight : 80px;\t\r\n");
      out.write("}\r\n");
      out.write("#portfolio-grid > div > div > div {\r\n");
      out.write("\ttext-align : center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#map {\t\r\n");
      out.write("\twidth: 800px;\r\n");
      out.write("\theight: 300px;\r\n");
      out.write("\tborder: 2px solid red;\r\n");
      out.write("\toverflow: auto;\r\n");
      out.write("\tbackground: white;\r\n");
      out.write("}\r\n");
      out.write("#img{\r\n");
      out.write("\twidth:50px;\r\n");
      out.write("\theight:50px;\r\n");
      out.write("}\r\n");
      out.write("#cart >div> img {\r\n");
      out.write("\twidth:90px;\r\n");
      out.write("\theight:60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#but {\r\n");
      out.write("\tborder-radius:50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("\r\n");
      out.write("<title>어서오세요. M마트입니다.</title>\r\n");
      out.write("<meta content=\"\" name=\"descriptison\">\r\n");
      out.write("<meta content=\"\" name=\"keywords\">\r\n");
      out.write("\r\n");
      out.write("<!-- Favicons -->\r\n");
      out.write("<link href=\"customer/assets/img/favicon.png\" rel=\"icon\">\r\n");
      out.write("<link href=\"customer/assets/img/apple-touch-icon.png\"\r\n");
      out.write("\trel=\"apple-touch-icon\">\r\n");
      out.write("\r\n");
      out.write("<!-- Google Fonts -->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=https://fonts.googleapis.com/css?family=Inconsolata:400,500,600,700|Raleway:400,400i,500,500i,600,600i,700,700i\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Vendor CSS Files -->\r\n");
      out.write("<link href=\"customer/assets/vendor/bootstrap/css/bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link href=\"customer/assets/vendor/icofont/icofont.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link href=\"customer/assets/vendor/aos/aos.css\" rel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"customer/assets/vendor/line-awesome/css/line-awesome.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"customer/assets/vendor/owl.carousel/assets/owl.carousel.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Template Main CSS File -->\r\n");
      out.write("<link href=\"customer/assets/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- =======================================================\r\n");
      out.write("  * Template Name: MyPortfolio - v2.1.0\r\n");
      out.write("  * Template URL: https://bootstrapmade.com/myportfolio-bootstrap-portfolio-website-template/\r\n");
      out.write("  * Author: BootstrapMade.com\r\n");
      out.write("  * License: https://bootstrapmade.com/license/\r\n");
      out.write("  ======================================================== -->\r\n");
      out.write("</head>\r\n");
      out.write("<script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var products = null;\r\n");
      out.write("var sum= 0;\r\n");
      out.write("\r\n");
      out.write("function todb(){\r\n");
      out.write("\tdocument.frm.action='pay.mc';\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("function display(data){\r\n");
      out.write("\t$(data).each(function(index,data){\r\n");
      out.write("\tvar result = '';\r\n");
      out.write("\tresult += '<div class=\"item ' +data.category+ ' col-sm-3 col-md-2 col-lg-3 mb-3\">';\r\n");
      out.write("\tresult += '<div class=\"item-wrap fancybox\">';\r\n");
      out.write("\tresult += '<div class=\"work-info\" id=\"menu\">';\r\n");
      out.write("\tresult += '<div num=\"'+index+'\">';\r\n");
      out.write("\tresult += '<p id=\"cs\">'+data.name+'</p>';\r\n");
      out.write("\tresult += '<p>'+data.stock+'</p>';\r\n");
      out.write("\tresult += '<p>'+data.price+'</p>';\r\n");
      out.write("\tresult += '</div>';\r\n");
      out.write("\tresult += '</div>';\r\n");
      out.write("\tresult += '<img style=\"width:250px;height:150px;\" class=\"img-fluid\" src=\"customer/img/'+data.img+'\">';\r\n");
      out.write("\tresult += '</div>';\r\n");
      out.write("\tresult += '</div>';\r\n");
      out.write("\t\r\n");
      out.write("\tif(data.name==\"케이크\"){\r\n");
      out.write("\t\t$(\"cs\").css(\"color\",\"red\");\r\n");
      out.write("\t}\r\n");
      out.write("\t$('#portfolio-grid').append(result);\r\n");
      out.write("\t});\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function getMain(){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("/* \t\ttype:'get', */\r\n");
      out.write("\t\t  url: 'menuselect.mc',\r\n");
      out.write("\t\t  dataType: 'json',\r\n");
      out.write("\t\tasync:false,\r\n");
      out.write("\t\tsuccess: function(ja){\r\n");
      out.write("\t\t\tproducts = ja;\r\n");
      out.write("\t\t\tdisplay(ja);\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror: function(){\r\n");
      out.write("\t\t\talert('get Error.........');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("function cart(n){\r\n");
      out.write("\tvar name = products[n].name;\r\n");
      out.write("\tvar price = products[n].price;\r\n");
      out.write("\tvar img = products[n].img;\r\n");
      out.write("\tvar count = products[n].count;\r\n");
      out.write("\tvar result = '';\r\n");
      out.write("    result += '<div num=\"'+n+'\" id=\"choose'+n+'\">';\r\n");
      out.write("\tresult += '<table class=\"table\" id=\"tt\">';\r\n");
      out.write("    result += '<tbody>';\r\n");
      out.write("    result += '<tr>';\r\n");
      out.write("    result += '<td>'+'<img src = \"customer/img/'+img+'\" id = \"img\">'+'</td>';\r\n");
      out.write("    result += '<td>'+name+'<input type = \"hidden\" name =\"menu_code\" value = \"'+products[n].menu_code+'\"><input type = \"hidden\" name =\"total\" value = \"'+products[n].count*price+'\"></td>';\r\n");
      out.write("    result += '<td>'+price+'<input type = \"hidden\" name =\"quantity\" value = \"'+products[n].count+'\"><input type = \"hidden\" name =\"menu_name\" value = \"'+products[n].name+'\"></td>';\r\n");
      out.write("    result += '<td>' + count +'</td><input type = \"hidden\" name =\"menu_price\" value = \"'+products[n].price+'\">';\r\n");
      out.write("    result += '<td>' + '<button id=\"but\">X</button>' +'</td>';\r\n");
      out.write("    result += '</tr>';\r\n");
      out.write("    result += '</tbody>';\r\n");
      out.write("    result += '</table>';\r\n");
      out.write("   // result += '<input type =\"button\" value =\".\" onclick=\"location.href='orderlistadd.mc?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${order.getMenu_code()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\">';\r\n");
      out.write("    result += '</div>';\r\n");
      out.write("    sum += price;\r\n");
      out.write("    $('#sum > span').text(sum);\r\n");
      out.write("    $('#cart').append(result);\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\tgetMain();\r\n");
      out.write("\t$('#menu > div').mouseover(function(){\r\n");
      out.write("\t\t$(this).css(\"cursor\", \"pointer\");\r\n");
      out.write("\t});\r\n");
      out.write("\t$('#menu > div').click(function(){\r\n");
      out.write("\t\tvar num = $(this).attr('num');\r\n");
      out.write("\t\tproducts[num].count += 1;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(products[num].count == 1){\r\n");
      out.write("\t\tcart(num);\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t$('#choose'+num).remove();\r\n");
      out.write("\t\t\tcart(num);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t$('#cart').on('click', '#but', function(){\r\n");
      out.write("         var num = $(this).parent().parent().parent().parent().parent().attr('num');\r\n");
      out.write("\t\tvar price = products[num].price;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(products[num].count == 1) {\r\n");
      out.write("\t\t\t$(this).parent().parent().remove();\r\n");
      out.write("\t\t\tproducts[num].count = 0;\r\n");
      out.write("\t\t\t sum -= price;\r\n");
      out.write("\t\t\t $('#sum > span').text(sum);\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tproducts[num].count = products[num].count - 1;\r\n");
      out.write("\t\t\t$('#choose'+num).remove();\r\n");
      out.write("\t\t\tcart(num);\r\n");
      out.write("\t        sum -= 2*price;\r\n");
      out.write("\t\t  \t$('#sum > span').text(sum);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("<section>\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\t<main id=\"main\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- ======= Works Section ======= -->\r\n");
      out.write("\t\t<section class=\"section site-portfolio\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row mb-5 align-items-center\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12 col-lg-6 mb-4 mb-lg-0\" data-aos=\"fade-up\">\r\n");
      out.write("\t\t\t\t\t\t<h2>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginuser.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("님 M 마트에 오신걸 환영합니다</h2>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"mb-0\">즐거운 쇼핑 되세요</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12 col-lg-6 text-left text-lg-right\"\r\n");
      out.write("\t\t\t\t\t\tdata-aos=\"fade-up\" data-aos-delay=\"100\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"filters\" class=\"filters\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" data-filter=\"*\" class=\"active\">All</a> <a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-filter=\".음식\">음식</a> <a href=\"#\" data-filter=\".음료\">음료</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" data-filter=\".아이스크림\">아이스크림</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"portfolio-grid\" class=\"row no-gutter\" data-aos=\"fade-up\"\r\n");
      out.write("\t\t\t\t\tdata-aos-delay=\"200\">\r\n");
      out.write("\t\t\t\t\t<!-- append -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<!-- End  Works Section -->\r\n");
      out.write("\t<div>\r\n");
      out.write("  <form class=\"pay-form\" action=\"pay.mc\" method=\"post\">\r\n");
      out.write("  \r\n");
      out.write("    <div class=\"container\" id=\"cart\">\r\n");
      out.write("    <table class = \"table\" id = \"tabl\">\r\n");
      out.write("    \t<thead><tr><th>선택메뉴</th><th>상품명</th><th>가격</th><th>개수</th><th>취소</th></tr></thead>\r\n");
      out.write("    </table>\r\n");
      out.write("    </div> \r\n");
      out.write("\r\n");
      out.write("    <!-- 총 결제 금액 -->\r\n");
      out.write("    <div class=\"col-md-5 form-group\">\r\n");
      out.write("             <h3 id=\"sum\" style=\"margin-left:330px;\">총 결제 금액 : <span id=\"tot\"></span></h3>\r\n");
      out.write("    </div>\r\n");
      out.write(" \t<div class=\"col-md-6 form-group\"> <!-- 결제하기 -->\r\n");
      out.write("             <button class=\"btn btn-primary btn-lg btn-block\" type=\"submit\" style=\"margin-left:330px;\">결제하기</button>\r\n");
      out.write("    </div>\r\n");
      out.write("    </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\t</main>\r\n");
      out.write("\t<!-- End #main -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<a href=\"#\" class=\"back-to-top\"><i class=\"icofont-simple-up\"></i></a>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Vendor JS Files -->\r\n");
      out.write("\t<script src=\"customer/assets/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"customer/assets/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\t<script src=\"customer/assets/vendor/jquery.easing/jquery.easing.min.js\"></script>\r\n");
      out.write("\t<script src=\"customer/assets/vendor/php-email-form/validate.js\"></script>\r\n");
      out.write("\t<script src=\"customer/assets/vendor/aos/aos.js\"></script>\r\n");
      out.write("\t<script src=\"customer/assets/vendor/isotope-layout/isotope.pkgd.min.js\"></script>\r\n");
      out.write("\t<script src=\"customer/assets/vendor/owl.carousel/owl.carousel.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Template Main JS File -->\r\n");
      out.write("\t<script src=\"customer/assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest)_jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse)_jspx_page_context.getResponse();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write('\r');
          out.write('\n');
          out.write('	');
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest)_jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse)_jspx_page_context.getResponse();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /customer/main.jsp(201,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginuser.id =='admin'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t");
          org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "adminnav.jsp", out, false);
          out.write("\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest)_jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse)_jspx_page_context.getResponse();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t");
          org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "nav.jsp", out, false);
          out.write("\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
