/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2020-09-03 06:22:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.customer;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mypage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/p01/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1598681847341L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("\r\n");
      out.write("  <title>회원가입</title>\r\n");
      out.write("  <meta content=\"\" name=\"descriptison\">\r\n");
      out.write("  <meta content=\"\" name=\"keywords\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Favicons -->\r\n");
      out.write("  <link href=\"customer/assets/img/favicon.png\" rel=\"icon\">\r\n");
      out.write("  <link href=\"customer/assets/img/apple-touch-icon.png\" rel=\"apple-touch-icon\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Google Fonts -->\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=https://fonts.googleapis.com/css?family=Inconsolata:400,500,600,700|Raleway:400,400i,500,500i,600,600i,700,700i\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Vendor CSS Files -->\r\n");
      out.write("  <link href=\"customer/assets/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"customer/assets/vendor/icofont/icofont.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"customer/assets/vendor/aos/aos.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"customer/assets/vendor/line-awesome/css/line-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"customer/assets/vendor/owl.carousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Template Main CSS File -->\r\n");
      out.write("  <link href=\"customer/assets/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- =======================================================\r\n");
      out.write("  * Template Name: MyPortfolio - v2.1.0\r\n");
      out.write("  * Template URL: https://bootstrapmade.com/myportfolio-bootstrap-portfolio-website-template/\r\n");
      out.write("  * Author: BootstrapMade.com\r\n");
      out.write("  * License: https://bootstrapmade.com/license/\r\n");
      out.write("  ======================================================== -->\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <!-- ======= Navbar ======= -->\r\n");
      out.write("  <div class=\"collapse navbar-collapse custom-navmenu\" id=\"main-navbar\">\r\n");
      out.write("    <div class=\"container py-2 py-md-5\">\r\n");
      out.write("      <div class=\"row align-items-start\">\r\n");
      out.write("        <div class=\"col-md-2\">\r\n");
      out.write("          <ul class=\"custom-menu\">\r\n");
      out.write("            <li><a href=\"main.mc\">홈</a></li>\r\n");
      out.write("            <li class=\"active\"><a href=\"mypage.mc\">마이 페이지</a></li>\r\n");
      out.write("            <li><a href=\"contact.mc\">건의사항</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"login.mc\">로그아웃</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"admin.mc\">관리자</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-6 d-none d-md-block  mr-auto\">\r\n");
      out.write("          <div class=\"tweet d-flex\">\r\n");
      out.write("            <span class=\"icofont-twitter text-white mt-2 mr-3\"></span>\r\n");
      out.write("            <div>\r\n");
      out.write("              <p><em>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam necessitatibus incidunt ut officiis explicabo inventore. <br> <a href=\"#\">t.co/v82jsk</a></em></p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-4 d-none d-md-block\">\r\n");
      out.write("          <h3>Hire Me</h3>\r\n");
      out.write("          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam necessitatibus incidunt ut officiisexplicabo inventore. <br> <a href=\"#\">myemail@gmail.com</a></p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <nav class=\"navbar navbar-light custom-navbar\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"main.mc\">내 정보</a>\r\n");
      out.write("\r\n");
      out.write("      <a href=\"#\" class=\"burger\" data-toggle=\"collapse\" data-target=\"#main-navbar\">\r\n");
      out.write("        <span></span>\r\n");
      out.write("      </a>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>\r\n");
      out.write("\r\n");
      out.write("  <main id=\"main\">\r\n");
      out.write("\r\n");
      out.write("    <section class=\"section pb-5\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row mb-5 align-items-end\">\r\n");
      out.write("          <div class=\"col-md-6\" data-aos=\"fade-up\">\r\n");
      out.write("            <h2>Contact</h2>\r\n");
      out.write("            <p class=\"mb-0\">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam necessitatibus incidunt ut\r\n");
      out.write("              officiis explicabo inventore.\r\n");
      out.write("            </p>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-6 mb-5 mb-md-0\" data-aos=\"fade-up\">\r\n");
      out.write("\r\n");
      out.write("            <form action=\"forms/contact.php\" method=\"post\" role=\"form\" class=\"php-email-form\">\r\n");
      out.write("\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-6 form-group\">\r\n");
      out.write("                  <label for=\"name\">Name</label>\r\n");
      out.write("                  <input type=\"text\" name=\"name\" class=\"form-control\" id=\"name\" data-rule=\"minlen:4\" data-msg=\"Please enter at least 4 chars\" />\r\n");
      out.write("                  <div class=\"validate\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 form-group\">\r\n");
      out.write("                  <label for=\"name\">Email</label>\r\n");
      out.write("                  <input type=\"email\" class=\"form-control\" name=\"email\" id=\"email\" data-rule=\"email\" data-msg=\"Please enter a valid email\" />\r\n");
      out.write("                  <div class=\"validate\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-12 form-group\">\r\n");
      out.write("                  <label for=\"name\">Subject</label>\r\n");
      out.write("                  <input type=\"text\" class=\"form-control\" name=\"subject\" id=\"subject\" data-rule=\"minlen:4\" data-msg=\"Please enter at least 8 chars of subject\" />\r\n");
      out.write("                  <div class=\"validate\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-12 form-group\">\r\n");
      out.write("                  <label for=\"name\">Message</label>\r\n");
      out.write("                  <textarea class=\"form-control\" name=\"message\" cols=\"30\" rows=\"10\" data-rule=\"required\" data-msg=\"Please write something for us\"></textarea>\r\n");
      out.write("                  <div class=\"validate\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-md-12 mb-3\">\r\n");
      out.write("                  <div class=\"loading\">Loading</div>\r\n");
      out.write("                  <div class=\"error-message\"></div>\r\n");
      out.write("                  <div class=\"sent-message\">Your message has been sent. Thank you!</div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-md-6 form-group\">\r\n");
      out.write("                  <input type=\"submit\" class=\"readmore d-block w-100\" value=\"Send Message\">\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("            </form>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-md-4 ml-auto order-2\" data-aos=\"fade-up\">\r\n");
      out.write("            <ul class=\"list-unstyled\">\r\n");
      out.write("              <li class=\"mb-3\">\r\n");
      out.write("                <strong class=\"d-block mb-1\">Address</strong>\r\n");
      out.write("                <span>203 Fake St. Mountain View, San Francisco, California, USA</span>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"mb-3\">\r\n");
      out.write("                <strong class=\"d-block mb-1\">Phone</strong>\r\n");
      out.write("                <span>+1 232 3235 324</span>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"mb-3\">\r\n");
      out.write("                <strong class=\"d-block mb-1\">Email</strong>\r\n");
      out.write("                <span>youremail@domain.com</span>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("  </main><!-- End #main -->\r\n");
      out.write("\r\n");
      out.write("  <!-- ======= Footer ======= -->\r\n");
      out.write("  <footer class=\"footer\" role=\"contentinfo\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-sm-6\">\r\n");
      out.write("          <p class=\"mb-1\">&copy; Copyright MyPortfolio. All Rights Reserved</p>\r\n");
      out.write("          <div class=\"credits\">\r\n");
      out.write("            <!--\r\n");
      out.write("            All the links in the footer should remain intact.\r\n");
      out.write("            You can delete the links only if you purchased the pro version.\r\n");
      out.write("            Licensing information: https://bootstrapmade.com/license/\r\n");
      out.write("            Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=MyPortfolio\r\n");
      out.write("          -->\r\n");
      out.write("            Designed by <a href=\"https://bootstrapmade.com/\">BootstrapMade</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-sm-6 social text-md-right\">\r\n");
      out.write("          <a href=\"#\"><span class=\"icofont-twitter\"></span></a>\r\n");
      out.write("          <a href=\"#\"><span class=\"icofont-facebook\"></span></a>\r\n");
      out.write("          <a href=\"#\"><span class=\"icofont-dribbble\"></span></a>\r\n");
      out.write("          <a href=\"#\"><span class=\"icofont-behance\"></span></a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer>\r\n");
      out.write("\r\n");
      out.write("  <a href=\"#\" class=\"back-to-top\"><i class=\"icofont-simple-up\"></i></a>\r\n");
      out.write("\r\n");
      out.write("  <!-- Vendor JS Files -->\r\n");
      out.write("  <script src=\"customer/assets/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"customer/assets/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  <script src=\"customer/assets/vendor/jquery.easing/jquery.easing.min.js\"></script>\r\n");
      out.write("  <script src=\"customer/assets/vendor/php-email-form/validate.js\"></script>\r\n");
      out.write("  <script src=\"customer/assets/vendor/aos/aos.js\"></script>\r\n");
      out.write("  <script src=\"customer/assets/vendor/isotope-layout/isotope.pkgd.min.js\"></script>\r\n");
      out.write("  <script src=\"customer/assets/vendor/owl.carousel/owl.carousel.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Template Main JS File -->\r\n");
      out.write("  <script src=\"customer/assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
