/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2020-09-11 14:59:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.customer.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class adminmenu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/p01/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1598681847341L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var products = null;\r\n");
      out.write("\r\n");
      out.write("function display(data){\r\n");
      out.write("\t$(data).each(function(index,data){\r\n");
      out.write("\tvar result = '';\r\n");
      out.write("\tif(data.name== '피자'){\r\n");
      out.write("\t\t$(\"#cs\").css(\"color\",\"red\");\r\n");
      out.write("\t}\r\n");
      out.write("\tresult += '<div class=\"item ' +data.category+ ' col-sm-2 col-md-2 col-lg-2 mb-3\">';\r\n");
      out.write("\tresult += '<a href=\"adminmenudetail.mc?menu_code='+data.menu_code+'\"><div id=\"cs\" style=\"text-align:center;\"><p><img style=\"width:150px;height:120px;\" class=\"img-fluid\" src=\"customer/img/'+data.img1+'\">'+data.name+'</p>';\r\n");
      out.write("\tresult += '<p>재고 : '+data.stock+'</p>';\r\n");
      out.write("\tresult += '<p>가격 : '+data.price+'</p>';\r\n");
      out.write("\tresult += '<p> 카테고리 : '+data.category+'</p>';\r\n");
      out.write("\tresult += '</div></a>';\r\n");
      out.write("\tresult += '</div>';\r\n");
      out.write("\t$('#portfolio-grid').append(result);\r\n");
      out.write("\t});\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("function getMain(){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("/* \t\ttype:'get', */\r\n");
      out.write("\t\t  url: 'adminmenuselect.mc',\r\n");
      out.write("\t\t  dataType: 'json',\r\n");
      out.write("\t\tasync:false,\r\n");
      out.write("\t\tsuccess: function(ja){\r\n");
      out.write("\t\t\tproducts = ja;\r\n");
      out.write("\t\t\tdisplay(ja);\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror: function(){\r\n");
      out.write("\t\t\talert('get Error.........');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\tgetMain();\r\n");
      out.write("})\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\t\t<!-- ======= Works Section ======= -->\r\n");
      out.write("\t\t<section class=\"section site-portfolio\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row mb-5 align-items-center\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12 col-lg-6 mb-4 mb-lg-0\" data-aos=\"fade-up\">\r\n");
      out.write("\t\t\t\t\t\t<h2>메뉴 관리 페이지</h2>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12 col-lg-6 text-left text-lg-right\"\r\n");
      out.write("\t\t\t\t\t\tdata-aos=\"fade-up\" data-aos-delay=\"100\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"filters\" class=\"filters\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" data-filter=\"*\" class=\"active\">All</a> <a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-filter=\".음식\">음식</a> <a href=\"#\" data-filter=\".음료\">음료</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" data-filter=\".아이스크림\">아이스크림</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t                <div class=\"col-md-3 form-group\">\r\n");
      out.write("                  <input type=\"button\" class=\"readmore d-block w-80\" value=\"메뉴 추가\" onclick=\"location.href='adminmenuadd.mc'\" data-aos=\"fade-up\">\r\n");
      out.write("                </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"portfolio-grid\" class=\"row no-gutter\" data-aos=\"fade-up\"\r\n");
      out.write("\t\t\t\t\tdata-aos-delay=\"200\">\r\n");
      out.write("\t\t\t\t\t<!-- append -->\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<!-- End  Works Section -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- End #main -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
